// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatProto.proto

// Protobuf Java Version: 3.25.5
package com.supply.api.chat;

public final class ChatProto {
  private ChatProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface webSocketOnCloseRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webSocketOnCloseRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   *消息请求类型
   * </pre>
   *
   * Protobuf type {@code webSocketOnCloseRequest}
   */
  public static final class webSocketOnCloseRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:webSocketOnCloseRequest)
      webSocketOnCloseRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use webSocketOnCloseRequest.newBuilder() to construct.
    private webSocketOnCloseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private webSocketOnCloseRequest() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new webSocketOnCloseRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.supply.api.chat.ChatProto.internal_static_webSocketOnCloseRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.supply.api.chat.ChatProto.internal_static_webSocketOnCloseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.supply.api.chat.ChatProto.webSocketOnCloseRequest.class, com.supply.api.chat.ChatProto.webSocketOnCloseRequest.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.supply.api.chat.ChatProto.webSocketOnCloseRequest)) {
        return super.equals(obj);
      }
      com.supply.api.chat.ChatProto.webSocketOnCloseRequest other = (com.supply.api.chat.ChatProto.webSocketOnCloseRequest) obj;

      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.supply.api.chat.ChatProto.webSocketOnCloseRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.supply.api.chat.ChatProto.webSocketOnCloseRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.supply.api.chat.ChatProto.webSocketOnCloseRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.supply.api.chat.ChatProto.webSocketOnCloseRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.supply.api.chat.ChatProto.webSocketOnCloseRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.supply.api.chat.ChatProto.webSocketOnCloseRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.supply.api.chat.ChatProto.webSocketOnCloseRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.supply.api.chat.ChatProto.webSocketOnCloseRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.supply.api.chat.ChatProto.webSocketOnCloseRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.supply.api.chat.ChatProto.webSocketOnCloseRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.supply.api.chat.ChatProto.webSocketOnCloseRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.supply.api.chat.ChatProto.webSocketOnCloseRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.supply.api.chat.ChatProto.webSocketOnCloseRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *消息请求类型
     * </pre>
     *
     * Protobuf type {@code webSocketOnCloseRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webSocketOnCloseRequest)
        com.supply.api.chat.ChatProto.webSocketOnCloseRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.supply.api.chat.ChatProto.internal_static_webSocketOnCloseRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.supply.api.chat.ChatProto.internal_static_webSocketOnCloseRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.supply.api.chat.ChatProto.webSocketOnCloseRequest.class, com.supply.api.chat.ChatProto.webSocketOnCloseRequest.Builder.class);
      }

      // Construct using com.supply.api.chat.ChatProto.webSocketOnCloseRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        message_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.supply.api.chat.ChatProto.internal_static_webSocketOnCloseRequest_descriptor;
      }

      @java.lang.Override
      public com.supply.api.chat.ChatProto.webSocketOnCloseRequest getDefaultInstanceForType() {
        return com.supply.api.chat.ChatProto.webSocketOnCloseRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.supply.api.chat.ChatProto.webSocketOnCloseRequest build() {
        com.supply.api.chat.ChatProto.webSocketOnCloseRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.supply.api.chat.ChatProto.webSocketOnCloseRequest buildPartial() {
        com.supply.api.chat.ChatProto.webSocketOnCloseRequest result = new com.supply.api.chat.ChatProto.webSocketOnCloseRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.supply.api.chat.ChatProto.webSocketOnCloseRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.message_ = message_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.supply.api.chat.ChatProto.webSocketOnCloseRequest) {
          return mergeFrom((com.supply.api.chat.ChatProto.webSocketOnCloseRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.supply.api.chat.ChatProto.webSocketOnCloseRequest other) {
        if (other == com.supply.api.chat.ChatProto.webSocketOnCloseRequest.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 1;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:webSocketOnCloseRequest)
    }

    // @@protoc_insertion_point(class_scope:webSocketOnCloseRequest)
    private static final com.supply.api.chat.ChatProto.webSocketOnCloseRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.supply.api.chat.ChatProto.webSocketOnCloseRequest();
    }

    public static com.supply.api.chat.ChatProto.webSocketOnCloseRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<webSocketOnCloseRequest>
        PARSER = new com.google.protobuf.AbstractParser<webSocketOnCloseRequest>() {
      @java.lang.Override
      public webSocketOnCloseRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<webSocketOnCloseRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<webSocketOnCloseRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.supply.api.chat.ChatProto.webSocketOnCloseRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface storeChatInformationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:storeChatInformationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>int64 queueId = 2;</code>
     * @return The queueId.
     */
    long getQueueId();

    /**
     * <code>int64 sendUserId = 3;</code>
     * @return The sendUserId.
     */
    long getSendUserId();

    /**
     * <code>int64 receiveUserId = 4;</code>
     * @return The receiveUserId.
     */
    long getReceiveUserId();

    /**
     * <code>string information = 5;</code>
     * @return The information.
     */
    java.lang.String getInformation();
    /**
     * <code>string information = 5;</code>
     * @return The bytes for information.
     */
    com.google.protobuf.ByteString
        getInformationBytes();

    /**
     * <code>string image = 6;</code>
     * @return The image.
     */
    java.lang.String getImage();
    /**
     * <code>string image = 6;</code>
     * @return The bytes for image.
     */
    com.google.protobuf.ByteString
        getImageBytes();

    /**
     * <code>.google.protobuf.Timestamp sendTime = 7;</code>
     * @return Whether the sendTime field is set.
     */
    boolean hasSendTime();
    /**
     * <code>.google.protobuf.Timestamp sendTime = 7;</code>
     * @return The sendTime.
     */
    com.google.protobuf.Timestamp getSendTime();
    /**
     * <code>.google.protobuf.Timestamp sendTime = 7;</code>
     */
    com.google.protobuf.TimestampOrBuilder getSendTimeOrBuilder();
  }
  /**
   * Protobuf type {@code storeChatInformationRequest}
   */
  public static final class storeChatInformationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:storeChatInformationRequest)
      storeChatInformationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use storeChatInformationRequest.newBuilder() to construct.
    private storeChatInformationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private storeChatInformationRequest() {
      information_ = "";
      image_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new storeChatInformationRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.supply.api.chat.ChatProto.internal_static_storeChatInformationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.supply.api.chat.ChatProto.internal_static_storeChatInformationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.supply.api.chat.ChatProto.storeChatInformationRequest.class, com.supply.api.chat.ChatProto.storeChatInformationRequest.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int QUEUEID_FIELD_NUMBER = 2;
    private long queueId_ = 0L;
    /**
     * <code>int64 queueId = 2;</code>
     * @return The queueId.
     */
    @java.lang.Override
    public long getQueueId() {
      return queueId_;
    }

    public static final int SENDUSERID_FIELD_NUMBER = 3;
    private long sendUserId_ = 0L;
    /**
     * <code>int64 sendUserId = 3;</code>
     * @return The sendUserId.
     */
    @java.lang.Override
    public long getSendUserId() {
      return sendUserId_;
    }

    public static final int RECEIVEUSERID_FIELD_NUMBER = 4;
    private long receiveUserId_ = 0L;
    /**
     * <code>int64 receiveUserId = 4;</code>
     * @return The receiveUserId.
     */
    @java.lang.Override
    public long getReceiveUserId() {
      return receiveUserId_;
    }

    public static final int INFORMATION_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object information_ = "";
    /**
     * <code>string information = 5;</code>
     * @return The information.
     */
    @java.lang.Override
    public java.lang.String getInformation() {
      java.lang.Object ref = information_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        information_ = s;
        return s;
      }
    }
    /**
     * <code>string information = 5;</code>
     * @return The bytes for information.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInformationBytes() {
      java.lang.Object ref = information_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        information_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object image_ = "";
    /**
     * <code>string image = 6;</code>
     * @return The image.
     */
    @java.lang.Override
    public java.lang.String getImage() {
      java.lang.Object ref = image_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        image_ = s;
        return s;
      }
    }
    /**
     * <code>string image = 6;</code>
     * @return The bytes for image.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getImageBytes() {
      java.lang.Object ref = image_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        image_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTIME_FIELD_NUMBER = 7;
    private com.google.protobuf.Timestamp sendTime_;
    /**
     * <code>.google.protobuf.Timestamp sendTime = 7;</code>
     * @return Whether the sendTime field is set.
     */
    @java.lang.Override
    public boolean hasSendTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp sendTime = 7;</code>
     * @return The sendTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getSendTime() {
      return sendTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp sendTime = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getSendTimeOrBuilder() {
      return sendTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (queueId_ != 0L) {
        output.writeInt64(2, queueId_);
      }
      if (sendUserId_ != 0L) {
        output.writeInt64(3, sendUserId_);
      }
      if (receiveUserId_ != 0L) {
        output.writeInt64(4, receiveUserId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(information_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, information_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(image_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, image_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(7, getSendTime());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (queueId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, queueId_);
      }
      if (sendUserId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sendUserId_);
      }
      if (receiveUserId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, receiveUserId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(information_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, information_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(image_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, image_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getSendTime());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.supply.api.chat.ChatProto.storeChatInformationRequest)) {
        return super.equals(obj);
      }
      com.supply.api.chat.ChatProto.storeChatInformationRequest other = (com.supply.api.chat.ChatProto.storeChatInformationRequest) obj;

      if (getId()
          != other.getId()) return false;
      if (getQueueId()
          != other.getQueueId()) return false;
      if (getSendUserId()
          != other.getSendUserId()) return false;
      if (getReceiveUserId()
          != other.getReceiveUserId()) return false;
      if (!getInformation()
          .equals(other.getInformation())) return false;
      if (!getImage()
          .equals(other.getImage())) return false;
      if (hasSendTime() != other.hasSendTime()) return false;
      if (hasSendTime()) {
        if (!getSendTime()
            .equals(other.getSendTime())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + QUEUEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getQueueId());
      hash = (37 * hash) + SENDUSERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendUserId());
      hash = (37 * hash) + RECEIVEUSERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReceiveUserId());
      hash = (37 * hash) + INFORMATION_FIELD_NUMBER;
      hash = (53 * hash) + getInformation().hashCode();
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
      if (hasSendTime()) {
        hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + getSendTime().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.supply.api.chat.ChatProto.storeChatInformationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.supply.api.chat.ChatProto.storeChatInformationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.supply.api.chat.ChatProto.storeChatInformationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.supply.api.chat.ChatProto.storeChatInformationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.supply.api.chat.ChatProto.storeChatInformationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.supply.api.chat.ChatProto.storeChatInformationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.supply.api.chat.ChatProto.storeChatInformationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.supply.api.chat.ChatProto.storeChatInformationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.supply.api.chat.ChatProto.storeChatInformationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.supply.api.chat.ChatProto.storeChatInformationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.supply.api.chat.ChatProto.storeChatInformationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.supply.api.chat.ChatProto.storeChatInformationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.supply.api.chat.ChatProto.storeChatInformationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code storeChatInformationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:storeChatInformationRequest)
        com.supply.api.chat.ChatProto.storeChatInformationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.supply.api.chat.ChatProto.internal_static_storeChatInformationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.supply.api.chat.ChatProto.internal_static_storeChatInformationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.supply.api.chat.ChatProto.storeChatInformationRequest.class, com.supply.api.chat.ChatProto.storeChatInformationRequest.Builder.class);
      }

      // Construct using com.supply.api.chat.ChatProto.storeChatInformationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSendTimeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        queueId_ = 0L;
        sendUserId_ = 0L;
        receiveUserId_ = 0L;
        information_ = "";
        image_ = "";
        sendTime_ = null;
        if (sendTimeBuilder_ != null) {
          sendTimeBuilder_.dispose();
          sendTimeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.supply.api.chat.ChatProto.internal_static_storeChatInformationRequest_descriptor;
      }

      @java.lang.Override
      public com.supply.api.chat.ChatProto.storeChatInformationRequest getDefaultInstanceForType() {
        return com.supply.api.chat.ChatProto.storeChatInformationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.supply.api.chat.ChatProto.storeChatInformationRequest build() {
        com.supply.api.chat.ChatProto.storeChatInformationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.supply.api.chat.ChatProto.storeChatInformationRequest buildPartial() {
        com.supply.api.chat.ChatProto.storeChatInformationRequest result = new com.supply.api.chat.ChatProto.storeChatInformationRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.supply.api.chat.ChatProto.storeChatInformationRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.queueId_ = queueId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sendUserId_ = sendUserId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.receiveUserId_ = receiveUserId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.information_ = information_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.image_ = image_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.sendTime_ = sendTimeBuilder_ == null
              ? sendTime_
              : sendTimeBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.supply.api.chat.ChatProto.storeChatInformationRequest) {
          return mergeFrom((com.supply.api.chat.ChatProto.storeChatInformationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.supply.api.chat.ChatProto.storeChatInformationRequest other) {
        if (other == com.supply.api.chat.ChatProto.storeChatInformationRequest.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getQueueId() != 0L) {
          setQueueId(other.getQueueId());
        }
        if (other.getSendUserId() != 0L) {
          setSendUserId(other.getSendUserId());
        }
        if (other.getReceiveUserId() != 0L) {
          setReceiveUserId(other.getReceiveUserId());
        }
        if (!other.getInformation().isEmpty()) {
          information_ = other.information_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getImage().isEmpty()) {
          image_ = other.image_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.hasSendTime()) {
          mergeSendTime(other.getSendTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                queueId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                sendUserId_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                receiveUserId_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                information_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                image_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                input.readMessage(
                    getSendTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long queueId_ ;
      /**
       * <code>int64 queueId = 2;</code>
       * @return The queueId.
       */
      @java.lang.Override
      public long getQueueId() {
        return queueId_;
      }
      /**
       * <code>int64 queueId = 2;</code>
       * @param value The queueId to set.
       * @return This builder for chaining.
       */
      public Builder setQueueId(long value) {

        queueId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 queueId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearQueueId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        queueId_ = 0L;
        onChanged();
        return this;
      }

      private long sendUserId_ ;
      /**
       * <code>int64 sendUserId = 3;</code>
       * @return The sendUserId.
       */
      @java.lang.Override
      public long getSendUserId() {
        return sendUserId_;
      }
      /**
       * <code>int64 sendUserId = 3;</code>
       * @param value The sendUserId to set.
       * @return This builder for chaining.
       */
      public Builder setSendUserId(long value) {

        sendUserId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sendUserId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sendUserId_ = 0L;
        onChanged();
        return this;
      }

      private long receiveUserId_ ;
      /**
       * <code>int64 receiveUserId = 4;</code>
       * @return The receiveUserId.
       */
      @java.lang.Override
      public long getReceiveUserId() {
        return receiveUserId_;
      }
      /**
       * <code>int64 receiveUserId = 4;</code>
       * @param value The receiveUserId to set.
       * @return This builder for chaining.
       */
      public Builder setReceiveUserId(long value) {

        receiveUserId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 receiveUserId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiveUserId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        receiveUserId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object information_ = "";
      /**
       * <code>string information = 5;</code>
       * @return The information.
       */
      public java.lang.String getInformation() {
        java.lang.Object ref = information_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          information_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string information = 5;</code>
       * @return The bytes for information.
       */
      public com.google.protobuf.ByteString
          getInformationBytes() {
        java.lang.Object ref = information_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          information_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string information = 5;</code>
       * @param value The information to set.
       * @return This builder for chaining.
       */
      public Builder setInformation(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        information_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string information = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearInformation() {
        information_ = getDefaultInstance().getInformation();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string information = 5;</code>
       * @param value The bytes for information to set.
       * @return This builder for chaining.
       */
      public Builder setInformationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        information_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object image_ = "";
      /**
       * <code>string image = 6;</code>
       * @return The image.
       */
      public java.lang.String getImage() {
        java.lang.Object ref = image_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          image_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string image = 6;</code>
       * @return The bytes for image.
       */
      public com.google.protobuf.ByteString
          getImageBytes() {
        java.lang.Object ref = image_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          image_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string image = 6;</code>
       * @param value The image to set.
       * @return This builder for chaining.
       */
      public Builder setImage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        image_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string image = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearImage() {
        image_ = getDefaultInstance().getImage();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string image = 6;</code>
       * @param value The bytes for image to set.
       * @return This builder for chaining.
       */
      public Builder setImageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        image_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp sendTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> sendTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp sendTime = 7;</code>
       * @return Whether the sendTime field is set.
       */
      public boolean hasSendTime() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 7;</code>
       * @return The sendTime.
       */
      public com.google.protobuf.Timestamp getSendTime() {
        if (sendTimeBuilder_ == null) {
          return sendTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
        } else {
          return sendTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 7;</code>
       */
      public Builder setSendTime(com.google.protobuf.Timestamp value) {
        if (sendTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sendTime_ = value;
        } else {
          sendTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 7;</code>
       */
      public Builder setSendTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (sendTimeBuilder_ == null) {
          sendTime_ = builderForValue.build();
        } else {
          sendTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 7;</code>
       */
      public Builder mergeSendTime(com.google.protobuf.Timestamp value) {
        if (sendTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0) &&
            sendTime_ != null &&
            sendTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getSendTimeBuilder().mergeFrom(value);
          } else {
            sendTime_ = value;
          }
        } else {
          sendTimeBuilder_.mergeFrom(value);
        }
        if (sendTime_ != null) {
          bitField0_ |= 0x00000040;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 7;</code>
       */
      public Builder clearSendTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sendTime_ = null;
        if (sendTimeBuilder_ != null) {
          sendTimeBuilder_.dispose();
          sendTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 7;</code>
       */
      public com.google.protobuf.Timestamp.Builder getSendTimeBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getSendTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 7;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getSendTimeOrBuilder() {
        if (sendTimeBuilder_ != null) {
          return sendTimeBuilder_.getMessageOrBuilder();
        } else {
          return sendTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getSendTimeFieldBuilder() {
        if (sendTimeBuilder_ == null) {
          sendTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getSendTime(),
                  getParentForChildren(),
                  isClean());
          sendTime_ = null;
        }
        return sendTimeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:storeChatInformationRequest)
    }

    // @@protoc_insertion_point(class_scope:storeChatInformationRequest)
    private static final com.supply.api.chat.ChatProto.storeChatInformationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.supply.api.chat.ChatProto.storeChatInformationRequest();
    }

    public static com.supply.api.chat.ChatProto.storeChatInformationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<storeChatInformationRequest>
        PARSER = new com.google.protobuf.AbstractParser<storeChatInformationRequest>() {
      @java.lang.Override
      public storeChatInformationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<storeChatInformationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<storeChatInformationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.supply.api.chat.ChatProto.storeChatInformationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface sendMessageToUserRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sendMessageToUserRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string content = 1;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 1;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>bool isInformation = 2;</code>
     * @return The isInformation.
     */
    boolean getIsInformation();

    /**
     * <code>int64 userId = 3;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>int64 toUserId = 4;</code>
     * @return The toUserId.
     */
    long getToUserId();

    /**
     * <code>.google.protobuf.Timestamp sendTime = 5;</code>
     * @return Whether the sendTime field is set.
     */
    boolean hasSendTime();
    /**
     * <code>.google.protobuf.Timestamp sendTime = 5;</code>
     * @return The sendTime.
     */
    com.google.protobuf.Timestamp getSendTime();
    /**
     * <code>.google.protobuf.Timestamp sendTime = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getSendTimeOrBuilder();
  }
  /**
   * Protobuf type {@code sendMessageToUserRequest}
   */
  public static final class sendMessageToUserRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sendMessageToUserRequest)
      sendMessageToUserRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use sendMessageToUserRequest.newBuilder() to construct.
    private sendMessageToUserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private sendMessageToUserRequest() {
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new sendMessageToUserRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.supply.api.chat.ChatProto.internal_static_sendMessageToUserRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.supply.api.chat.ChatProto.internal_static_sendMessageToUserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.supply.api.chat.ChatProto.sendMessageToUserRequest.class, com.supply.api.chat.ChatProto.sendMessageToUserRequest.Builder.class);
    }

    private int bitField0_;
    public static final int CONTENT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object content_ = "";
    /**
     * <code>string content = 1;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 1;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISINFORMATION_FIELD_NUMBER = 2;
    private boolean isInformation_ = false;
    /**
     * <code>bool isInformation = 2;</code>
     * @return The isInformation.
     */
    @java.lang.Override
    public boolean getIsInformation() {
      return isInformation_;
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private long userId_ = 0L;
    /**
     * <code>int64 userId = 3;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int TOUSERID_FIELD_NUMBER = 4;
    private long toUserId_ = 0L;
    /**
     * <code>int64 toUserId = 4;</code>
     * @return The toUserId.
     */
    @java.lang.Override
    public long getToUserId() {
      return toUserId_;
    }

    public static final int SENDTIME_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp sendTime_;
    /**
     * <code>.google.protobuf.Timestamp sendTime = 5;</code>
     * @return Whether the sendTime field is set.
     */
    @java.lang.Override
    public boolean hasSendTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp sendTime = 5;</code>
     * @return The sendTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getSendTime() {
      return sendTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp sendTime = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getSendTimeOrBuilder() {
      return sendTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
      }
      if (isInformation_ != false) {
        output.writeBool(2, isInformation_);
      }
      if (userId_ != 0L) {
        output.writeInt64(3, userId_);
      }
      if (toUserId_ != 0L) {
        output.writeInt64(4, toUserId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(5, getSendTime());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
      }
      if (isInformation_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isInformation_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, userId_);
      }
      if (toUserId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, toUserId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getSendTime());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.supply.api.chat.ChatProto.sendMessageToUserRequest)) {
        return super.equals(obj);
      }
      com.supply.api.chat.ChatProto.sendMessageToUserRequest other = (com.supply.api.chat.ChatProto.sendMessageToUserRequest) obj;

      if (!getContent()
          .equals(other.getContent())) return false;
      if (getIsInformation()
          != other.getIsInformation()) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (getToUserId()
          != other.getToUserId()) return false;
      if (hasSendTime() != other.hasSendTime()) return false;
      if (hasSendTime()) {
        if (!getSendTime()
            .equals(other.getSendTime())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + ISINFORMATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsInformation());
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + TOUSERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getToUserId());
      if (hasSendTime()) {
        hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + getSendTime().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.supply.api.chat.ChatProto.sendMessageToUserRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.supply.api.chat.ChatProto.sendMessageToUserRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.supply.api.chat.ChatProto.sendMessageToUserRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.supply.api.chat.ChatProto.sendMessageToUserRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.supply.api.chat.ChatProto.sendMessageToUserRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.supply.api.chat.ChatProto.sendMessageToUserRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.supply.api.chat.ChatProto.sendMessageToUserRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.supply.api.chat.ChatProto.sendMessageToUserRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.supply.api.chat.ChatProto.sendMessageToUserRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.supply.api.chat.ChatProto.sendMessageToUserRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.supply.api.chat.ChatProto.sendMessageToUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.supply.api.chat.ChatProto.sendMessageToUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.supply.api.chat.ChatProto.sendMessageToUserRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sendMessageToUserRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sendMessageToUserRequest)
        com.supply.api.chat.ChatProto.sendMessageToUserRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.supply.api.chat.ChatProto.internal_static_sendMessageToUserRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.supply.api.chat.ChatProto.internal_static_sendMessageToUserRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.supply.api.chat.ChatProto.sendMessageToUserRequest.class, com.supply.api.chat.ChatProto.sendMessageToUserRequest.Builder.class);
      }

      // Construct using com.supply.api.chat.ChatProto.sendMessageToUserRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSendTimeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        content_ = "";
        isInformation_ = false;
        userId_ = 0L;
        toUserId_ = 0L;
        sendTime_ = null;
        if (sendTimeBuilder_ != null) {
          sendTimeBuilder_.dispose();
          sendTimeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.supply.api.chat.ChatProto.internal_static_sendMessageToUserRequest_descriptor;
      }

      @java.lang.Override
      public com.supply.api.chat.ChatProto.sendMessageToUserRequest getDefaultInstanceForType() {
        return com.supply.api.chat.ChatProto.sendMessageToUserRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.supply.api.chat.ChatProto.sendMessageToUserRequest build() {
        com.supply.api.chat.ChatProto.sendMessageToUserRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.supply.api.chat.ChatProto.sendMessageToUserRequest buildPartial() {
        com.supply.api.chat.ChatProto.sendMessageToUserRequest result = new com.supply.api.chat.ChatProto.sendMessageToUserRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.supply.api.chat.ChatProto.sendMessageToUserRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.isInformation_ = isInformation_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.toUserId_ = toUserId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.sendTime_ = sendTimeBuilder_ == null
              ? sendTime_
              : sendTimeBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.supply.api.chat.ChatProto.sendMessageToUserRequest) {
          return mergeFrom((com.supply.api.chat.ChatProto.sendMessageToUserRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.supply.api.chat.ChatProto.sendMessageToUserRequest other) {
        if (other == com.supply.api.chat.ChatProto.sendMessageToUserRequest.getDefaultInstance()) return this;
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getIsInformation() != false) {
          setIsInformation(other.getIsInformation());
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getToUserId() != 0L) {
          setToUserId(other.getToUserId());
        }
        if (other.hasSendTime()) {
          mergeSendTime(other.getSendTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                isInformation_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                userId_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                toUserId_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                input.readMessage(
                    getSendTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 1;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 1;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 1;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string content = 1;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private boolean isInformation_ ;
      /**
       * <code>bool isInformation = 2;</code>
       * @return The isInformation.
       */
      @java.lang.Override
      public boolean getIsInformation() {
        return isInformation_;
      }
      /**
       * <code>bool isInformation = 2;</code>
       * @param value The isInformation to set.
       * @return This builder for chaining.
       */
      public Builder setIsInformation(boolean value) {

        isInformation_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool isInformation = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsInformation() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isInformation_ = false;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 3;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 3;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {

        userId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private long toUserId_ ;
      /**
       * <code>int64 toUserId = 4;</code>
       * @return The toUserId.
       */
      @java.lang.Override
      public long getToUserId() {
        return toUserId_;
      }
      /**
       * <code>int64 toUserId = 4;</code>
       * @param value The toUserId to set.
       * @return This builder for chaining.
       */
      public Builder setToUserId(long value) {

        toUserId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 toUserId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearToUserId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        toUserId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp sendTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> sendTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp sendTime = 5;</code>
       * @return Whether the sendTime field is set.
       */
      public boolean hasSendTime() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 5;</code>
       * @return The sendTime.
       */
      public com.google.protobuf.Timestamp getSendTime() {
        if (sendTimeBuilder_ == null) {
          return sendTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
        } else {
          return sendTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 5;</code>
       */
      public Builder setSendTime(com.google.protobuf.Timestamp value) {
        if (sendTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sendTime_ = value;
        } else {
          sendTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 5;</code>
       */
      public Builder setSendTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (sendTimeBuilder_ == null) {
          sendTime_ = builderForValue.build();
        } else {
          sendTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 5;</code>
       */
      public Builder mergeSendTime(com.google.protobuf.Timestamp value) {
        if (sendTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            sendTime_ != null &&
            sendTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getSendTimeBuilder().mergeFrom(value);
          } else {
            sendTime_ = value;
          }
        } else {
          sendTimeBuilder_.mergeFrom(value);
        }
        if (sendTime_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 5;</code>
       */
      public Builder clearSendTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sendTime_ = null;
        if (sendTimeBuilder_ != null) {
          sendTimeBuilder_.dispose();
          sendTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getSendTimeBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getSendTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getSendTimeOrBuilder() {
        if (sendTimeBuilder_ != null) {
          return sendTimeBuilder_.getMessageOrBuilder();
        } else {
          return sendTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getSendTimeFieldBuilder() {
        if (sendTimeBuilder_ == null) {
          sendTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getSendTime(),
                  getParentForChildren(),
                  isClean());
          sendTime_ = null;
        }
        return sendTimeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sendMessageToUserRequest)
    }

    // @@protoc_insertion_point(class_scope:sendMessageToUserRequest)
    private static final com.supply.api.chat.ChatProto.sendMessageToUserRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.supply.api.chat.ChatProto.sendMessageToUserRequest();
    }

    public static com.supply.api.chat.ChatProto.sendMessageToUserRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<sendMessageToUserRequest>
        PARSER = new com.google.protobuf.AbstractParser<sendMessageToUserRequest>() {
      @java.lang.Override
      public sendMessageToUserRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<sendMessageToUserRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<sendMessageToUserRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.supply.api.chat.ChatProto.sendMessageToUserRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webSocketOnCloseRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webSocketOnCloseRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_storeChatInformationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_storeChatInformationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sendMessageToUserRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sendMessageToUserRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ChatProto.proto\032\033google/protobuf/empty" +
      ".proto\032\037google/protobuf/timestamp.proto\"" +
      "*\n\027webSocketOnCloseRequest\022\017\n\007message\030\001 " +
      "\001(\t\"\267\001\n\033storeChatInformationRequest\022\n\n\002i" +
      "d\030\001 \001(\003\022\017\n\007queueId\030\002 \001(\003\022\022\n\nsendUserId\030\003" +
      " \001(\003\022\025\n\rreceiveUserId\030\004 \001(\003\022\023\n\013informati" +
      "on\030\005 \001(\t\022\r\n\005image\030\006 \001(\t\022,\n\010sendTime\030\007 \001(" +
      "\0132\032.google.protobuf.Timestamp\"\222\001\n\030sendMe" +
      "ssageToUserRequest\022\017\n\007content\030\001 \001(\t\022\025\n\ri" +
      "sInformation\030\002 \001(\010\022\016\n\006userId\030\003 \001(\003\022\020\n\010to" +
      "UserId\030\004 \001(\003\022,\n\010sendTime\030\005 \001(\0132\032.google." +
      "protobuf.Timestamp2\351\001\n\013ChatService\022D\n\020we" +
      "bSocketOnClose\022\030.webSocketOnCloseRequest" +
      "\032\026.google.protobuf.Empty\022L\n\024storeChatInf" +
      "ormation\022\034.storeChatInformationRequest\032\026" +
      ".google.protobuf.Empty\022F\n\021sendMessageToU" +
      "ser\022\031.sendMessageToUserRequest\032\026.google." +
      "protobuf.EmptyB\"\n\023com.supply.api.chatB\tC" +
      "hatProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_webSocketOnCloseRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_webSocketOnCloseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webSocketOnCloseRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_storeChatInformationRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_storeChatInformationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_storeChatInformationRequest_descriptor,
        new java.lang.String[] { "Id", "QueueId", "SendUserId", "ReceiveUserId", "Information", "Image", "SendTime", });
    internal_static_sendMessageToUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sendMessageToUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sendMessageToUserRequest_descriptor,
        new java.lang.String[] { "Content", "IsInformation", "UserId", "ToUserId", "SendTime", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
