server:
  port: 10103
logging:
  file:
    name: user-service/src/main/resources/templates/logs.log
  level:
    com:
      supply:
        mapper: debug
        service: debug
        controller: debug
drug:
  auth:
    exclude-paths:
      - /user/register
      - /user/verifyCode/send
      - /user/resetPassword
      - /user/reUpload
springdoc:
  group-configs:
    - group: '药品供应管理系统项目用户服务接口文档'
      paths-to-match: '/**'
      packages-to-scan: com.supply.controller

