// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SeckillProto.proto

// Protobuf Java Version: 3.25.5
package com.supply.api.seckill;

public final class SeckillProto {
  private SeckillProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StoreFlashSaleInformationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StoreFlashSaleInformationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 flashSaleDrugId = 1;</code>
     * @return The flashSaleDrugId.
     */
    long getFlashSaleDrugId();

    /**
     * <code>string orderNumber = 2;</code>
     * @return The orderNumber.
     */
    java.lang.String getOrderNumber();
    /**
     * <code>string orderNumber = 2;</code>
     * @return The bytes for orderNumber.
     */
    com.google.protobuf.ByteString
        getOrderNumberBytes();

    /**
     * <code>int64 userId = 3;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>int32 status = 4;</code>
     * @return The status.
     */
    int getStatus();

    /**
     * <pre>
     * 使用标准的时间戳类型
     * </pre>
     *
     * <code>.google.protobuf.Timestamp orderTime = 5;</code>
     * @return Whether the orderTime field is set.
     */
    boolean hasOrderTime();
    /**
     * <pre>
     * 使用标准的时间戳类型
     * </pre>
     *
     * <code>.google.protobuf.Timestamp orderTime = 5;</code>
     * @return The orderTime.
     */
    com.google.protobuf.Timestamp getOrderTime();
    /**
     * <pre>
     * 使用标准的时间戳类型
     * </pre>
     *
     * <code>.google.protobuf.Timestamp orderTime = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getOrderTimeOrBuilder();
  }
  /**
   * <pre>
   * 消息请求类型
   * </pre>
   *
   * Protobuf type {@code StoreFlashSaleInformationRequest}
   */
  public static final class StoreFlashSaleInformationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StoreFlashSaleInformationRequest)
      StoreFlashSaleInformationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StoreFlashSaleInformationRequest.newBuilder() to construct.
    private StoreFlashSaleInformationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StoreFlashSaleInformationRequest() {
      orderNumber_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StoreFlashSaleInformationRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.supply.api.seckill.SeckillProto.internal_static_StoreFlashSaleInformationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.supply.api.seckill.SeckillProto.internal_static_StoreFlashSaleInformationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest.class, com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest.Builder.class);
    }

    private int bitField0_;
    public static final int FLASHSALEDRUGID_FIELD_NUMBER = 1;
    private long flashSaleDrugId_ = 0L;
    /**
     * <code>int64 flashSaleDrugId = 1;</code>
     * @return The flashSaleDrugId.
     */
    @java.lang.Override
    public long getFlashSaleDrugId() {
      return flashSaleDrugId_;
    }

    public static final int ORDERNUMBER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object orderNumber_ = "";
    /**
     * <code>string orderNumber = 2;</code>
     * @return The orderNumber.
     */
    @java.lang.Override
    public java.lang.String getOrderNumber() {
      java.lang.Object ref = orderNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string orderNumber = 2;</code>
     * @return The bytes for orderNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOrderNumberBytes() {
      java.lang.Object ref = orderNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private long userId_ = 0L;
    /**
     * <code>int64 userId = 3;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_ = 0;
    /**
     * <code>int32 status = 4;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    public static final int ORDERTIME_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp orderTime_;
    /**
     * <pre>
     * 使用标准的时间戳类型
     * </pre>
     *
     * <code>.google.protobuf.Timestamp orderTime = 5;</code>
     * @return Whether the orderTime field is set.
     */
    @java.lang.Override
    public boolean hasOrderTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 使用标准的时间戳类型
     * </pre>
     *
     * <code>.google.protobuf.Timestamp orderTime = 5;</code>
     * @return The orderTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getOrderTime() {
      return orderTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : orderTime_;
    }
    /**
     * <pre>
     * 使用标准的时间戳类型
     * </pre>
     *
     * <code>.google.protobuf.Timestamp orderTime = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getOrderTimeOrBuilder() {
      return orderTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : orderTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (flashSaleDrugId_ != 0L) {
        output.writeInt64(1, flashSaleDrugId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orderNumber_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orderNumber_);
      }
      if (userId_ != 0L) {
        output.writeInt64(3, userId_);
      }
      if (status_ != 0) {
        output.writeInt32(4, status_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(5, getOrderTime());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (flashSaleDrugId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, flashSaleDrugId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orderNumber_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orderNumber_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, userId_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, status_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getOrderTime());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest)) {
        return super.equals(obj);
      }
      com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest other = (com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest) obj;

      if (getFlashSaleDrugId()
          != other.getFlashSaleDrugId()) return false;
      if (!getOrderNumber()
          .equals(other.getOrderNumber())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (hasOrderTime() != other.hasOrderTime()) return false;
      if (hasOrderTime()) {
        if (!getOrderTime()
            .equals(other.getOrderTime())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FLASHSALEDRUGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFlashSaleDrugId());
      hash = (37 * hash) + ORDERNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getOrderNumber().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      if (hasOrderTime()) {
        hash = (37 * hash) + ORDERTIME_FIELD_NUMBER;
        hash = (53 * hash) + getOrderTime().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 消息请求类型
     * </pre>
     *
     * Protobuf type {@code StoreFlashSaleInformationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StoreFlashSaleInformationRequest)
        com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.supply.api.seckill.SeckillProto.internal_static_StoreFlashSaleInformationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.supply.api.seckill.SeckillProto.internal_static_StoreFlashSaleInformationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest.class, com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest.Builder.class);
      }

      // Construct using com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOrderTimeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        flashSaleDrugId_ = 0L;
        orderNumber_ = "";
        userId_ = 0L;
        status_ = 0;
        orderTime_ = null;
        if (orderTimeBuilder_ != null) {
          orderTimeBuilder_.dispose();
          orderTimeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.supply.api.seckill.SeckillProto.internal_static_StoreFlashSaleInformationRequest_descriptor;
      }

      @java.lang.Override
      public com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest getDefaultInstanceForType() {
        return com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest build() {
        com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest buildPartial() {
        com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest result = new com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.flashSaleDrugId_ = flashSaleDrugId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.orderNumber_ = orderNumber_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.status_ = status_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.orderTime_ = orderTimeBuilder_ == null
              ? orderTime_
              : orderTimeBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest) {
          return mergeFrom((com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest other) {
        if (other == com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest.getDefaultInstance()) return this;
        if (other.getFlashSaleDrugId() != 0L) {
          setFlashSaleDrugId(other.getFlashSaleDrugId());
        }
        if (!other.getOrderNumber().isEmpty()) {
          orderNumber_ = other.orderNumber_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (other.hasOrderTime()) {
          mergeOrderTime(other.getOrderTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                flashSaleDrugId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                orderNumber_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                userId_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                status_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                input.readMessage(
                    getOrderTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long flashSaleDrugId_ ;
      /**
       * <code>int64 flashSaleDrugId = 1;</code>
       * @return The flashSaleDrugId.
       */
      @java.lang.Override
      public long getFlashSaleDrugId() {
        return flashSaleDrugId_;
      }
      /**
       * <code>int64 flashSaleDrugId = 1;</code>
       * @param value The flashSaleDrugId to set.
       * @return This builder for chaining.
       */
      public Builder setFlashSaleDrugId(long value) {

        flashSaleDrugId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 flashSaleDrugId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlashSaleDrugId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        flashSaleDrugId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object orderNumber_ = "";
      /**
       * <code>string orderNumber = 2;</code>
       * @return The orderNumber.
       */
      public java.lang.String getOrderNumber() {
        java.lang.Object ref = orderNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string orderNumber = 2;</code>
       * @return The bytes for orderNumber.
       */
      public com.google.protobuf.ByteString
          getOrderNumberBytes() {
        java.lang.Object ref = orderNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderNumber = 2;</code>
       * @param value The orderNumber to set.
       * @return This builder for chaining.
       */
      public Builder setOrderNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        orderNumber_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string orderNumber = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderNumber() {
        orderNumber_ = getDefaultInstance().getOrderNumber();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string orderNumber = 2;</code>
       * @param value The bytes for orderNumber to set.
       * @return This builder for chaining.
       */
      public Builder setOrderNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        orderNumber_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 3;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 3;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {

        userId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 4;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {

        status_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp orderTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> orderTimeBuilder_;
      /**
       * <pre>
       * 使用标准的时间戳类型
       * </pre>
       *
       * <code>.google.protobuf.Timestamp orderTime = 5;</code>
       * @return Whether the orderTime field is set.
       */
      public boolean hasOrderTime() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * 使用标准的时间戳类型
       * </pre>
       *
       * <code>.google.protobuf.Timestamp orderTime = 5;</code>
       * @return The orderTime.
       */
      public com.google.protobuf.Timestamp getOrderTime() {
        if (orderTimeBuilder_ == null) {
          return orderTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : orderTime_;
        } else {
          return orderTimeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 使用标准的时间戳类型
       * </pre>
       *
       * <code>.google.protobuf.Timestamp orderTime = 5;</code>
       */
      public Builder setOrderTime(com.google.protobuf.Timestamp value) {
        if (orderTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          orderTime_ = value;
        } else {
          orderTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 使用标准的时间戳类型
       * </pre>
       *
       * <code>.google.protobuf.Timestamp orderTime = 5;</code>
       */
      public Builder setOrderTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (orderTimeBuilder_ == null) {
          orderTime_ = builderForValue.build();
        } else {
          orderTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 使用标准的时间戳类型
       * </pre>
       *
       * <code>.google.protobuf.Timestamp orderTime = 5;</code>
       */
      public Builder mergeOrderTime(com.google.protobuf.Timestamp value) {
        if (orderTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            orderTime_ != null &&
            orderTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getOrderTimeBuilder().mergeFrom(value);
          } else {
            orderTime_ = value;
          }
        } else {
          orderTimeBuilder_.mergeFrom(value);
        }
        if (orderTime_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * 使用标准的时间戳类型
       * </pre>
       *
       * <code>.google.protobuf.Timestamp orderTime = 5;</code>
       */
      public Builder clearOrderTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        orderTime_ = null;
        if (orderTimeBuilder_ != null) {
          orderTimeBuilder_.dispose();
          orderTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 使用标准的时间戳类型
       * </pre>
       *
       * <code>.google.protobuf.Timestamp orderTime = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getOrderTimeBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getOrderTimeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 使用标准的时间戳类型
       * </pre>
       *
       * <code>.google.protobuf.Timestamp orderTime = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getOrderTimeOrBuilder() {
        if (orderTimeBuilder_ != null) {
          return orderTimeBuilder_.getMessageOrBuilder();
        } else {
          return orderTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : orderTime_;
        }
      }
      /**
       * <pre>
       * 使用标准的时间戳类型
       * </pre>
       *
       * <code>.google.protobuf.Timestamp orderTime = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getOrderTimeFieldBuilder() {
        if (orderTimeBuilder_ == null) {
          orderTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getOrderTime(),
                  getParentForChildren(),
                  isClean());
          orderTime_ = null;
        }
        return orderTimeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StoreFlashSaleInformationRequest)
    }

    // @@protoc_insertion_point(class_scope:StoreFlashSaleInformationRequest)
    private static final com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest();
    }

    public static com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StoreFlashSaleInformationRequest>
        PARSER = new com.google.protobuf.AbstractParser<StoreFlashSaleInformationRequest>() {
      @java.lang.Override
      public StoreFlashSaleInformationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StoreFlashSaleInformationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StoreFlashSaleInformationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.supply.api.seckill.SeckillProto.StoreFlashSaleInformationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InventoryDeductionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InventoryDeductionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();
  }
  /**
   * Protobuf type {@code InventoryDeductionRequest}
   */
  public static final class InventoryDeductionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InventoryDeductionRequest)
      InventoryDeductionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InventoryDeductionRequest.newBuilder() to construct.
    private InventoryDeductionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InventoryDeductionRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InventoryDeductionRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.supply.api.seckill.SeckillProto.internal_static_InventoryDeductionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.supply.api.seckill.SeckillProto.internal_static_InventoryDeductionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.supply.api.seckill.SeckillProto.InventoryDeductionRequest.class, com.supply.api.seckill.SeckillProto.InventoryDeductionRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.supply.api.seckill.SeckillProto.InventoryDeductionRequest)) {
        return super.equals(obj);
      }
      com.supply.api.seckill.SeckillProto.InventoryDeductionRequest other = (com.supply.api.seckill.SeckillProto.InventoryDeductionRequest) obj;

      if (getId()
          != other.getId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.supply.api.seckill.SeckillProto.InventoryDeductionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.supply.api.seckill.SeckillProto.InventoryDeductionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.supply.api.seckill.SeckillProto.InventoryDeductionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.supply.api.seckill.SeckillProto.InventoryDeductionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.supply.api.seckill.SeckillProto.InventoryDeductionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.supply.api.seckill.SeckillProto.InventoryDeductionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.supply.api.seckill.SeckillProto.InventoryDeductionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.supply.api.seckill.SeckillProto.InventoryDeductionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.supply.api.seckill.SeckillProto.InventoryDeductionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.supply.api.seckill.SeckillProto.InventoryDeductionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.supply.api.seckill.SeckillProto.InventoryDeductionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.supply.api.seckill.SeckillProto.InventoryDeductionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.supply.api.seckill.SeckillProto.InventoryDeductionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InventoryDeductionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InventoryDeductionRequest)
        com.supply.api.seckill.SeckillProto.InventoryDeductionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.supply.api.seckill.SeckillProto.internal_static_InventoryDeductionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.supply.api.seckill.SeckillProto.internal_static_InventoryDeductionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.supply.api.seckill.SeckillProto.InventoryDeductionRequest.class, com.supply.api.seckill.SeckillProto.InventoryDeductionRequest.Builder.class);
      }

      // Construct using com.supply.api.seckill.SeckillProto.InventoryDeductionRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.supply.api.seckill.SeckillProto.internal_static_InventoryDeductionRequest_descriptor;
      }

      @java.lang.Override
      public com.supply.api.seckill.SeckillProto.InventoryDeductionRequest getDefaultInstanceForType() {
        return com.supply.api.seckill.SeckillProto.InventoryDeductionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.supply.api.seckill.SeckillProto.InventoryDeductionRequest build() {
        com.supply.api.seckill.SeckillProto.InventoryDeductionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.supply.api.seckill.SeckillProto.InventoryDeductionRequest buildPartial() {
        com.supply.api.seckill.SeckillProto.InventoryDeductionRequest result = new com.supply.api.seckill.SeckillProto.InventoryDeductionRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.supply.api.seckill.SeckillProto.InventoryDeductionRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.supply.api.seckill.SeckillProto.InventoryDeductionRequest) {
          return mergeFrom((com.supply.api.seckill.SeckillProto.InventoryDeductionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.supply.api.seckill.SeckillProto.InventoryDeductionRequest other) {
        if (other == com.supply.api.seckill.SeckillProto.InventoryDeductionRequest.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:InventoryDeductionRequest)
    }

    // @@protoc_insertion_point(class_scope:InventoryDeductionRequest)
    private static final com.supply.api.seckill.SeckillProto.InventoryDeductionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.supply.api.seckill.SeckillProto.InventoryDeductionRequest();
    }

    public static com.supply.api.seckill.SeckillProto.InventoryDeductionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InventoryDeductionRequest>
        PARSER = new com.google.protobuf.AbstractParser<InventoryDeductionRequest>() {
      @java.lang.Override
      public InventoryDeductionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<InventoryDeductionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InventoryDeductionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.supply.api.seckill.SeckillProto.InventoryDeductionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StoreFlashSaleInformationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StoreFlashSaleInformationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InventoryDeductionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InventoryDeductionRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SeckillProto.proto\032\033google/protobuf/em" +
      "pty.proto\032\037google/protobuf/timestamp.pro" +
      "to\"\237\001\n StoreFlashSaleInformationRequest\022" +
      "\027\n\017flashSaleDrugId\030\001 \001(\003\022\023\n\013orderNumber\030" +
      "\002 \001(\t\022\016\n\006userId\030\003 \001(\003\022\016\n\006status\030\004 \001(\005\022-\n" +
      "\torderTime\030\005 \001(\0132\032.google.protobuf.Times" +
      "tamp\"\'\n\031InventoryDeductionRequest\022\n\n\002id\030" +
      "\001 \001(\0032\262\001\n\016SeckillService\022V\n\031storeFlashSa" +
      "leInformation\022!.StoreFlashSaleInformatio" +
      "nRequest\032\026.google.protobuf.Empty\022H\n\022inve" +
      "ntoryDeduction\022\032.InventoryDeductionReque" +
      "st\032\026.google.protobuf.EmptyB(\n\026com.supply" +
      ".api.seckillB\014SeckillProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_StoreFlashSaleInformationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StoreFlashSaleInformationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StoreFlashSaleInformationRequest_descriptor,
        new java.lang.String[] { "FlashSaleDrugId", "OrderNumber", "UserId", "Status", "OrderTime", });
    internal_static_InventoryDeductionRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_InventoryDeductionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InventoryDeductionRequest_descriptor,
        new java.lang.String[] { "Id", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
