server:
  port: 10102
drug:
  jwt:
    secretKey: drugSupply
    ttl: 1209600000
    tokenName: token
  auth:
    exclude-paths:
      - /authorization
      - /user/register
      - /user/verifyCode/send
      - /user/resetPassword
      - /user/reUpload