server:
  port: 10102
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.65.151:8848
    gateway:
      routes:
        - id: authorization
          uri: lb://authorization-service
          predicates:
            - Path=/authorization
        - id: admin
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
        - id: chat
          uri: lb://chat-service
          predicates:
            - Path=/chat/**
        - id: medical
          uri: lb://medical-service
          predicates:
            - Path=/medical/**
        - id: seckill
          uri: lb://seckill-service
          predicates:
            - Path=/seckill/**
        - id: supply
          uri: lb://supply-service
          predicates:
            - Path=/supply/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**
drug:
  jwt:
    secretKey: drugSupply
    ttl: 1209600000
    tokenName: token
  auth:
    exclude-paths:
      - /authorization
      - /user/register
      - /user/verifyCode/send
      - /user/resetPassword
      - /user/reUpload